image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
environment:
  site: firesquare.ru
tasks:
- package: |
    cd $site
    tar -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
    acurl -f https://pages.sr.ht/publish/frsqr.xyz -Fcontent=@site.tar.gz
